<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Acessando e criando Funções, Importação e exportação dados | ENG 792 - Análise e visualização de dados com R (RStudio)</title>
  <meta name="description" content="Este é o material de supporte aos alunos matriculados na disciplina ENG 792 ofertada pelo programa de pós-gradução em Meteorologia Aplicada do Departamento de Engenharia Agrícola (DEA) da Universidade Federal de Viçosa (UFV)." />
  <meta name="generator" content="bookdown 0.22.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Acessando e criando Funções, Importação e exportação dados | ENG 792 - Análise e visualização de dados com R (RStudio)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é o material de supporte aos alunos matriculados na disciplina ENG 792 ofertada pelo programa de pós-gradução em Meteorologia Aplicada do Departamento de Engenharia Agrícola (DEA) da Universidade Federal de Viçosa (UFV)." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Acessando e criando Funções, Importação e exportação dados | ENG 792 - Análise e visualização de dados com R (RStudio)" />
  
  <meta name="twitter:description" content="Este é o material de supporte aos alunos matriculados na disciplina ENG 792 ofertada pelo programa de pós-gradução em Meteorologia Aplicada do Departamento de Engenharia Agrícola (DEA) da Universidade Federal de Viçosa (UFV)." />
  

<meta name="author" content="Jackson Rodrigues" />


<meta name="date" content="2021-08-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="acessando-e-manipulação-de-dados.html"/>

<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/es6shim-0.35.6/es6shim.js"></script>
<script src="libs/es7shim-6.0.0/es7shim.js"></script>
<script src="libs/graphre-0.1.3/graphre.js"></script>
<script src="libs/nomnoml-1.3.1/nomnoml.js"></script>
<script src="libs/nomnoml-binding-0.2.3/nomnoml.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ENG_792-AVDR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Apresentação</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#hello-world---sejam-bem-vindos"><i class="fa fa-check"></i><b>1.1</b> Hello World! - Sejam Bem Vindos!</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#sobre"><i class="fa fa-check"></i><b>1.1.1</b> Sobre</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#utilização"><i class="fa fa-check"></i><b>1.1.2</b> Utilização</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#códigos-e-dados"><i class="fa fa-check"></i><b>1.1.3</b> Códigos e Dados</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#cronograma-de-aulas"><i class="fa fa-check"></i><b>1.1.4</b> Cronograma de aulas</a></li>
<li class="chapter" data-level="1.1.5" data-path="index.html"><a href="index.html#métodos-de-avaliação"><i class="fa fa-check"></i><b>1.1.5</b> Métodos de avaliação</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html"><i class="fa fa-check"></i><b>2</b> Vamos ao que interesa</a>
<ul>
<li class="chapter" data-level="2.1" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#conhecendo-o-r"><i class="fa fa-check"></i><b>2.1</b> Conhecendo o R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#o-que-é-o-r"><i class="fa fa-check"></i><b>2.1.1</b> O que é o R?</a></li>
<li class="chapter" data-level="2.1.2" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#instalação-do-r"><i class="fa fa-check"></i><b>2.1.2</b> Instalação do R</a></li>
<li class="chapter" data-level="2.1.3" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#primeiro-contato"><i class="fa fa-check"></i><b>2.1.3</b> Primeiro contato</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#como-r-funciona"><i class="fa fa-check"></i><b>2.2</b> Como R funciona</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#tipos-de-objetos-mode-ou-type"><i class="fa fa-check"></i><b>2.2.1</b> Tipos de objetos (<em>mode</em> ou <em>type</em>)</a></li>
<li class="chapter" data-level="2.2.2" data-path="vamos-ao-que-interesa.html"><a href="vamos-ao-que-interesa.html#estrutura-do-objetos-class"><i class="fa fa-check"></i><b>2.2.2</b> Estrutura do objetos (<em>class</em>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="3" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html"><i class="fa fa-check"></i><b>3</b> Acessando e manipulação de dados</a>
<ul>
<li class="chapter" data-level="3.1" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#organização"><i class="fa fa-check"></i><b>3.1</b> Organização</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#usando---subscribing-ou-indexing"><i class="fa fa-check"></i><b>3.1.1</b> Usando [ ] - Subscribing ou indexing</a></li>
<li class="chapter" data-level="3.1.2" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#grep"><i class="fa fa-check"></i><b>3.1.2</b> grep()</a></li>
<li class="chapter" data-level="3.1.3" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#grepl"><i class="fa fa-check"></i><b>3.1.3</b> grepl()</a></li>
<li class="chapter" data-level="3.1.4" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#sub-e-gsub"><i class="fa fa-check"></i><b>3.1.4</b> sub() e gsub()</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#operadores"><i class="fa fa-check"></i><b>3.2</b> Operadores</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#iterações"><i class="fa fa-check"></i><b>3.2.1</b> Iterações</a></li>
<li class="chapter" data-level="3.2.2" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#condicionais"><i class="fa fa-check"></i><b>3.2.2</b> Condicionais</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#dica-de-leitura"><i class="fa fa-check"></i><b>3.3</b> Dica de leitura</a></li>
<li class="chapter" data-level="3.4" data-path="acessando-e-manipulação-de-dados.html"><a href="acessando-e-manipulação-de-dados.html#exercícios"><i class="fa fa-check"></i><b>3.4</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html"><i class="fa fa-check"></i><b>4</b> Acessando e criando Funções, Importação e exportação dados</a>
<ul>
<li class="chapter" data-level="4.1" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#funções"><i class="fa fa-check"></i><b>4.1</b> Funções</a></li>
<li class="chapter" data-level="4.2" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#pacotes"><i class="fa fa-check"></i><b>4.2</b> Pacotes</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#o-que-são-de-onde-vem-para-onde-vão-do-que-se-alimentam"><i class="fa fa-check"></i><b>4.2.1</b> O que são? De onde vem? Para onde vão? Do que se alimentam?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#entrando-com-dados"><i class="fa fa-check"></i><b>4.3</b> Entrando com dados</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#edit"><i class="fa fa-check"></i><b>4.3.1</b> edit()</a></li>
<li class="chapter" data-level="4.3.2" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#built-in"><i class="fa fa-check"></i><b>4.3.2</b> built-in</a></li>
<li class="chapter" data-level="4.3.3" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#scan"><i class="fa fa-check"></i><b>4.3.3</b> scan()</a></li>
<li class="chapter" data-level="4.3.4" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#lendo-arquivos-de-texto-.txt"><i class="fa fa-check"></i><b>4.3.4</b> Lendo arquivos de texto (.txt)</a></li>
<li class="chapter" data-level="4.3.5" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#read.csv"><i class="fa fa-check"></i><b>4.3.5</b> read.csv()</a></li>
<li class="chapter" data-level="4.3.6" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#planilhas-excel-completas-.xls-ou-.xlsx"><i class="fa fa-check"></i><b>4.3.6</b> Planilhas excel completas (.xls ou .xlsx)</a></li>
<li class="chapter" data-level="4.3.7" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#exportar-arquivos"><i class="fa fa-check"></i><b>4.3.7</b> Exportar arquivos()</a></li>
<li class="chapter" data-level="4.3.8" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#definir-diretório-de-trabalho-setwd"><i class="fa fa-check"></i><b>4.3.8</b> Definir diretório de trabalho <code>setwd()</code></a></li>
<li class="chapter" data-level="4.3.9" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#exercícios-1"><i class="fa fa-check"></i><b>4.3.9</b> Exercícios</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="acessando-e-criando-funções-importação-e-exportação-dados.html"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#dica-de-leitura-1"><i class="fa fa-check"></i><b>4.4</b> Dica de leitura</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ENG 792 - Análise e visualização de dados com R (RStudio)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="acessando-e-criando-funções-importação-e-exportação-dados" class="section level1" number="4">
<h1><span class="header-section-number">Capítulo 4</span> Acessando e criando Funções, Importação e exportação dados</h1>
<div id="funções" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Funções</h2>
<p>Assista este conteúdo em <strong>Cap 3 - Funções</strong> no <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<p>Embora existam uma grande variedade de <em>funções</em> e <em>pacotes</em> disponíveis e crescendo em número, a grande versatilidade do R nos permite criar <em>comandos/funções</em> personalizadas.<br />
No entanto, uma dúvida que por ventura você tenha e não consida sanar dentro das opções de ajuda do próprio R, buscar em fóruns sobre o assunto pode ser uma saída, pois geralmente a sua dúvida foi a dúvida de alguém antes de você.</p>
<p>Vamos inicialmente dar uma olhada nas funções do próprio R.
Até aqui vimos algumas funções como: <code>c(), seq(), rep(), print(), is.numeric(), is.integer(), is.double(), is.character(), typeof(), which(), grep() e etc</code></p>
<p>Para entender melhor como uma <em>função</em> funciona ou o que ela faz e permite fazer podemos pedir ajuda escrevendo <code>?nomedafunção</code>.
Por exemplo:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb386-1" aria-hidden="true" tabindex="-1"></a>?rnorm <span class="co">#Gera um vetor de números aleatórios normalmente ditribuídos</span></span></code></pre></div>
<p>No display de ajuda da função <code>rnorm()</code>observamos como a função deve ser utilizada, quais parâmetros devem ser inseridos.<br />
<code>rnorm(n, mean = 0, sd = 1)</code></p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">5</span> ,<span class="dv">10</span> , <span class="dv">8</span>) <span class="co">#Vejam que não estão próximas de zero, mas de dez. </span></span></code></pre></div>
<pre><code>## [1] 10.832136 20.693150  7.485574 10.044467 -3.818861</code></pre>
<p>Podemos dar nomes aos parâmetros também, caso não sejam nomeados, os parâmetros seguirão a ordem estabelecida na função original inciada em <em>n</em> seguida de <em>mean</em> e <em>sd</em>.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb389-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb389-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">5</span> ,<span class="at">mean=</span><span class="dv">10</span> , <span class="at">sd=</span><span class="dv">8</span>) </span></code></pre></div>
<pre><code>## [1]  0.343474 12.219434 18.675529 -8.765582 13.432998</code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb391-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb391-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">mean=</span><span class="dv">10</span>,<span class="at">n=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">8</span>) <span class="co"># Uma vez nomeados, eles podem ser arranjados da maneira que desejar. </span></span></code></pre></div>
<pre><code>## [1]  0.343474 12.219434 18.675529 -8.765582 13.432998</code></pre>
<p>Quando você executou <code>?rnorm</code>, você deve ter percebido que existem outro comandos semelhantes:</p>
<p><code>dnorm(x, mean = 0, sd = 1, log = FALSE)</code><br />
<code>pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)</code>
<code>qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)</code></p>
<p><code>dnorm</code> retorna o valor da função de densidade de probabilidade para os parâmetros. fornececidos.</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.04102012</code></pre>
<p><code>pnorm</code> retorna a integral de <em>-Inf</em> até <em>q</em> de um <em>pdf</em> ( <em>Probability density function</em>) da distribuição normal onde <em>q</em> é o <em>z-score</em>.</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">5</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.2659855</code></pre>
<p><code>qnorm</code> é simplesmente o inverso do <em>cdf</em> ( <em>cumulative distribution function</em>), no qual você pode entender com o inverso de <code>pnorm</code>.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb397-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(.<span class="dv">2</span>) <span class="co"># Responde como o z-score do vigèsimo elemento de uma distribuiçãop normal.</span></span></code></pre></div>
<pre><code>## [1] -0.8416212</code></pre>
<p>Para mais detalhes sobre estas funções <a href="http://seankross.com/notes/dpqr/">clique aqui</a>.</p>
<p>As funções acima e tantas outras estão disponíveis no <strong>R</strong> desde sua instalação, assim como as funções básicas abaixo.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
função
</th>
<th style="text-align:left;">
Descrição
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
abs(x)
</td>
<td style="text-align:left;">
Valor absoluto
</td>
</tr>
<tr>
<td style="text-align:left;">
sqrt(x)
</td>
<td style="text-align:left;">
Raiz quadrada
</td>
</tr>
<tr>
<td style="text-align:left;">
ceiling(x)
</td>
<td style="text-align:left;">
Arredonda para o inteiro acima
</td>
</tr>
<tr>
<td style="text-align:left;">
floor(x)
</td>
<td style="text-align:left;">
Arredonda para o inteiro abaixo
</td>
</tr>
<tr>
<td style="text-align:left;">
trunc(x)
</td>
<td style="text-align:left;">
Trunca para um inteiro
</td>
</tr>
<tr>
<td style="text-align:left;">
round(x,digits=n)
</td>
<td style="text-align:left;">
Arredonda de acordo com número de casas decimais
</td>
</tr>
<tr>
<td style="text-align:left;">
log(x)
</td>
<td style="text-align:left;">
Logarítimo natural
</td>
</tr>
<tr>
<td style="text-align:left;">
log10(x)
</td>
<td style="text-align:left;">
Logarítmo decimal
</td>
</tr>
<tr>
<td style="text-align:left;">
exp(x)
</td>
<td style="text-align:left;">
Exponenciação de base e com expoente x
</td>
</tr>
<tr>
<td style="text-align:left;">
sin(x)
</td>
<td style="text-align:left;">
Seno em radianos
</td>
</tr>
<tr>
<td style="text-align:left;">
cos(x)
</td>
<td style="text-align:left;">
Cosseno em radianos
</td>
</tr>
<tr>
<td style="text-align:left;">
tan(x)
</td>
<td style="text-align:left;">
Tangente em radianos
</td>
</tr>
</tbody>
</table>
<pre><code>## [1] 9.99</code></pre>
<pre><code>## [1] 1.772454</code></pre>
<pre><code>## [1] 4</code></pre>
<pre><code>## [1] 3</code></pre>
<pre><code>## [1] 3</code></pre>
<pre><code>## [1] 3.14</code></pre>
<pre><code>## [1] 1.14473</code></pre>
<pre><code>## [1] 0.4971499</code></pre>
<pre><code>## [1] 23.14069</code></pre>
<pre><code>## [1] 1.224606e-16</code></pre>
<pre><code>## [1] -1</code></pre>
<pre><code>## [1] -1.224647e-16</code></pre>
<p>Pesquise por <code>asin(), acos(), atan()</code>.</p>
<p>Embora seja rico de opções, com funções dos mais variados tipos e aplicações às vezes não encontramos aquelas específicas que precisamos para algo específico. Ou, mesmo que esteja desenvolvendo uma metodologia nova com novos <em>approaches</em> ou um novo <strong>pacote</strong> você precisará impreterivelmente de criar suas próprias funções.</p>
<p>As funções às vezes não são tão simples para uma primeira tentativa de uso ou criação principalmente para aqueles que estão iniciando em R ou qualquer linguagem de programação.
Podemos imaginar a função dividida em 3 partes (entrada, processamento e sapida) como uma caixa com muito buracos de uma lado ( <em>inputs</em>) e apenas um buraco do outro ( <em>output</em>) e a caixa atua de acordo com nossos comandos. Ou ainda como processamento de frutas para um suco.</p>
<div class="figure">
<img src="Cap_3_funcoes.png" alt="" />
<p class="caption">Estrutura de uma função</p>
</div>
<p>Estrutura de uma função:
* A função recebe um nome que recebe os argumentos e comandos a serem executados. O nome da função será o comando a ser executado sempre que desejado.</p>
<ul>
<li><p>Após o atribuidor vem o comando <em>function</em> seguindo de <em>()</em>. Dentro de <em>()</em> vem os argumentos (posição ou nomes) que são as variáveis ou outras informações inseridas pelo usuário.</p></li>
<li><p>Após fechar os parênteses abre-se chaves <em>{}</em> onde entram as equações ou testes a serem executados e as opções de saídas com o comando <strong>return</strong> quer geralmente encontra-se ao final da função. Não há restrição sobre a estrutura ou tipo de objeto retornado (<code>list, data.frame, matrix, numeric, logical</code> … etc).</p></li>
<li><p>Após o registro da função no ambiente do R (Veja o <em>global environment</em>), a função fica pronta para uso.</p></li>
</ul>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb411-1" aria-hidden="true" tabindex="-1"></a>minhafunção <span class="ot">&lt;-</span> <span class="cf">function</span>(arg1, arg2, ... ){</span>
<span id="cb411-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb411-2" aria-hidden="true" tabindex="-1"></a>    statements</span>
<span id="cb411-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb411-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(object)</span>
<span id="cb411-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb411-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Vamos criar uma função de divisão.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb412-1" aria-hidden="true" tabindex="-1"></a>divisao <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y) { </span>
<span id="cb412-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb412-2" aria-hidden="true" tabindex="-1"></a>    resultado <span class="ot">&lt;-</span> x<span class="sc">/</span>y </span>
<span id="cb412-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb412-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(resultado) </span>
<span id="cb412-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb412-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<ol style="list-style-type: decimal">
<li>A função se chama <code>divisao</code>.</li>
<li>Declare as variáveis <strong>x, y</strong> entre <strong>()</strong>;</li>
<li><strong>{}</strong> guardam os comandos a serem executados;</li>
<li><code>resultado &lt;- x/y</code> e <code>print(resultado)</code> são os comandos a serem executados.</li>
</ol>
<div id="htmlwidget-9a1ac9816b7991afc326" style="width:672px;height:480px;" class="nomnoml html-widget"></div>
<script type="application/json" data-for="htmlwidget-9a1ac9816b7991afc326">{"x":{"code":"#.if: visual=rhomb fill=#e2efda align=center\n#.for: visual=rhomb fill=#ddebf7 align=center\n#.repeat: visual=rhomb fill=#fce4d6 align=center\n#.while: visual=rhomb fill=#fff2cc align=center\n#.standard: visual=class fill=#ededed align=left\n#.commented: visual=class fill=#ededed\n#.header: visual=roundrect fill=#d9e1f2 align=left\n#.return: visual=end fill=#70ad47  empty\n#.stop: visual=end fill=#ed7d31  empty\n#.break: visual=receiver fill=#ffc000 empty\n#.next: visual=transceiver fill=#5b9bd5  empty\n#arrowSize: 1\n#bendSize: 0.3\n#direction: down\n#gutter: 5\n#edgeMargin: 0\n#edges: hard\n#fill: #eee8d5\n#fillArrows: false\n#font: Courier\n#fontSize: 12\n#leading: 1.25\n#lineWidth: 3\n#padding: 16\n#spacing: 40\n#stroke: #33322E\n#title: filename\n#zoom: 1\n#acyclicer: greedy\n#ranker: network-simplex\n\n[<header>divisao(x, y)]  -> [<standard> 1: ;resultado <- x / y\nprint(resultado)]\n[<standard> 1: ;resultado <- x / y\nprint(resultado)]  -> [<return> 2:]","svg":true},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb413-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(<span class="dv">50</span>,<span class="dv">25</span>)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb415-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(<span class="dv">22</span>,<span class="fl">4.4</span>)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb417-1" aria-hidden="true" tabindex="-1"></a>g<span class="ot">&lt;-</span><span class="dv">5</span></span>
<span id="cb417-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb417-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="dv">10</span></span>
<span id="cb417-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb417-3" aria-hidden="true" tabindex="-1"></a>a<span class="ot">&lt;-</span>x</span>
<span id="cb417-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb417-4" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(g,a)</span></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(a<span class="sc">+</span>g,g)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Experimentem e vejam o que acontece.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(<span class="dv">50</span>,)</span></code></pre></div>
<pre><code>## Error in divisao(50, ): argument &quot;y&quot; is missing, with no default</code></pre>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb423-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(<span class="dv">50</span>,<span class="dv">25</span>,<span class="dv">32</span>)</span></code></pre></div>
<pre><code>## Error in divisao(50, 25, 32): unused argument (32)</code></pre>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb425-1" aria-hidden="true" tabindex="-1"></a><span class="fu">divisao</span>(a,m)</span></code></pre></div>
<pre><code>## , , 1
## 
##           [,1]     [,2]      [,3]
## [1,] 10.000000 2.000000 1.1111111
## [2,]  5.000000 1.666667 1.0000000
## [3,]  3.333333 1.428571 0.9090909
## [4,]  2.500000 1.250000 0.8333333
## 
## , , 2
## 
##           [,1]      [,2]      [,3]
## [1,] 0.7692308 0.5882353 0.4761905
## [2,] 0.7142857 0.5555556 0.4545455
## [3,] 0.6666667 0.5263158 0.4347826
## [4,] 0.6250000 0.5000000 0.4166667</code></pre>
<p>***Escreva uma função teste chamada <code>multiplicador</code> que multiplica os valores 12.8, 19.2 e <em>pi</em>. _pi_é armazenado internamente pelo R com 6 casas decimais e pode ser chamada escrevendo <em>pi</em>.***</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb427-1" aria-hidden="true" tabindex="-1"></a>multiplicador <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, z) {</span>
<span id="cb427-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb427-2" aria-hidden="true" tabindex="-1"></a>    resultado <span class="ot">&lt;-</span> x<span class="sc">*</span>y<span class="sc">*</span>z </span>
<span id="cb427-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb427-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(resultado) } <span class="co"># `print` mostra o resultado de um objeto ou operação</span></span>
<span id="cb427-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb427-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb427-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb427-5" aria-hidden="true" tabindex="-1"></a><span class="fu">multiplicador</span>(<span class="fl">12.8</span>, <span class="fl">19.2</span>, pi)</span></code></pre></div>
<pre><code>## [1] 772.0778</code></pre>
<p><strong><em>Escreva uma função teste chamada <code>multiplicador</code> que multiplica os valores um vetor com 50 números por outro de 50 números e armazene o resultado como G sem mostrá-los na tela</em></strong></p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb429-1" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from=</span> <span class="dv">1</span>,<span class="at">to=</span><span class="dv">10</span>, <span class="at">length.out=</span><span class="dv">50</span>); </span>
<span id="cb429-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb429-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(s) </span></code></pre></div>
<pre><code>## [1] 50</code></pre>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb431-1" aria-hidden="true" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>##  [1]  1.000000  1.183673  1.367347  1.551020  1.734694  1.918367
##  [7]  2.102041  2.285714  2.469388  2.653061  2.836735  3.020408
## [13]  3.204082  3.387755  3.571429  3.755102  3.938776  4.122449
## [19]  4.306122  4.489796  4.673469  4.857143  5.040816  5.224490
## [25]  5.408163  5.591837  5.775510  5.959184  6.142857  6.326531
## [31]  6.510204  6.693878  6.877551  7.061224  7.244898  7.428571
## [37]  7.612245  7.795918  7.979592  8.163265  8.346939  8.530612
## [43]  8.714286  8.897959  9.081633  9.265306  9.448980  9.632653
## [49]  9.816327 10.000000</code></pre>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb433-1" aria-hidden="true" tabindex="-1"></a>d<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">1</span>,<span class="at">to=</span><span class="dv">10</span>,<span class="at">length.out =</span> <span class="fu">length</span>(s))</span>
<span id="cb433-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb433-2" aria-hidden="true" tabindex="-1"></a>d</span></code></pre></div>
<pre><code>##  [1]  1.000000  1.183673  1.367347  1.551020  1.734694  1.918367
##  [7]  2.102041  2.285714  2.469388  2.653061  2.836735  3.020408
## [13]  3.204082  3.387755  3.571429  3.755102  3.938776  4.122449
## [19]  4.306122  4.489796  4.673469  4.857143  5.040816  5.224490
## [25]  5.408163  5.591837  5.775510  5.959184  6.142857  6.326531
## [31]  6.510204  6.693878  6.877551  7.061224  7.244898  7.428571
## [37]  7.612245  7.795918  7.979592  8.163265  8.346939  8.530612
## [43]  8.714286  8.897959  9.081633  9.265306  9.448980  9.632653
## [49]  9.816327 10.000000</code></pre>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-1" aria-hidden="true" tabindex="-1"></a>multiplicador <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y){</span>
<span id="cb435-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-2" aria-hidden="true" tabindex="-1"></a>  resultado <span class="ot">&lt;-</span> x<span class="sc">*</span>y</span>
<span id="cb435-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">assign</span>(<span class="st">&quot;resultado&quot;</span>, resultado, <span class="at">envir=</span><span class="fu">globalenv</span>())</span>
<span id="cb435-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-4" aria-hidden="true" tabindex="-1"></a>  } <span class="co"># `assign` atribui os valores de uma operação a um objeto</span></span>
<span id="cb435-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb435-6"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-6" aria-hidden="true" tabindex="-1"></a><span class="fu">multiplicador</span>(s,d)</span>
<span id="cb435-7"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb435-7" aria-hidden="true" tabindex="-1"></a>resultado</span></code></pre></div>
<pre><code>##  [1]   1.000000   1.401083   1.869638   2.405664   3.009163   3.680133
##  [7]   4.418576   5.224490   6.097876   7.038734   8.047064   9.122865
## [13]  10.266139  11.476885  12.755102  14.100791  15.513953  16.994586
## [19]  18.542691  20.158267  21.841316  23.591837  25.409829  27.295294
## [25]  29.248230  31.268638  33.356518  35.511870  37.734694  40.024990
## [31]  42.382757  44.807997  47.300708  49.860891  52.488546  55.183673
## [37]  57.946272  60.776343  63.673886  66.638900  69.671387  72.771345
## [43]  75.938776  79.173678  82.476052  85.845898  89.283215  92.788005
## [49]  96.360267 100.000000</code></pre>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-1" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="cf">function</span>( <span class="at">x =</span> <span class="fu">c</span>( <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)){ </span>
<span id="cb437-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Neste caso utilizamos valores default que permitem testes caso algo saia errado</span></span>
<span id="cb437-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Calcula média do inpout x</span></span>
<span id="cb437-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-4" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">sum</span>(x)<span class="sc">/</span><span class="fu">length</span>(x)</span>
<span id="cb437-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>( out) <span class="co"># `return` devolve/retorna/mostra os resultado de uma operação ou objeto</span></span>
<span id="cb437-6"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb437-7"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb437-8"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-8" aria-hidden="true" tabindex="-1"></a>minha.media <span class="ot">&lt;-</span> <span class="fu">media</span>( <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span> <span class="dv">100</span>) <span class="co"># print result print( my.mean)</span></span>
<span id="cb437-9"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb437-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(minha.media)</span></code></pre></div>
<pre><code>## [1] 50.5</code></pre>
<p>As funções também permitem maior interação com usuário para a tomada de uma decisão por exemplo.</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-1" aria-hidden="true" tabindex="-1"></a>mensagem <span class="ot">&lt;-</span> <span class="cf">function</span>( <span class="at">arg1=</span><span class="fu">readline</span>(<span class="at">prompt=</span><span class="st">&quot;escreva sua mensagem: &quot;</span>), <span class="at">arg2 =</span> <span class="fu">readline</span>(<span class="at">prompt=</span><span class="st">&quot;De novo: &quot;</span>)){ </span>
<span id="cb439-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-2" aria-hidden="true" tabindex="-1"></a>  msg1 <span class="ot">&lt;-</span> <span class="fu">paste0</span>(arg1) </span>
<span id="cb439-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-3" aria-hidden="true" tabindex="-1"></a>  msg2 <span class="ot">&lt;-</span> <span class="fu">paste0</span>(arg2) </span>
<span id="cb439-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>( msg1, msg2)</span>
<span id="cb439-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-5" aria-hidden="true" tabindex="-1"></a>   }</span>
<span id="cb439-6"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb439-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mensagem</span>()</span></code></pre></div>
<pre><code>## Olá Mundo! Hello World!</code></pre>
</div>
<div id="pacotes" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Pacotes</h2>
<p>Assista este conteúdo em <strong>Cap 3 - Pacotes</strong> no <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<div id="o-que-são-de-onde-vem-para-onde-vão-do-que-se-alimentam" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> O que são? De onde vem? Para onde vão? Do que se alimentam?</h3>
<p>Quando iniciamos o R pouco mais de 2000 funções e outros objetos na memória estão prontos para uso.</p>
<p>No R temos os pacotes que são feitos para cálculos estatísticos dos mais variados, pacotes para fazer gráficos, pacotes aplicados à um determinado tipo de dado ou subdivisão da ciência e etc…</p>
<p>Eles basicamente permitem vocês expandirem a funcionalidade do R para programação, ao invés de escrever dezenas de linhas de códigos, esses códigos são preparados, empacotados e tudo que você precisa fazer e usá-lo.
Os <code>Packages</code> são coleções de funções, dados, e códigos compilados num formato bem definido. O diretório onde os pacotes estão armazenados são chamados <code>library</code>. A função
<code>.libPaths()</code> onde sua biblioteca está alojada.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb441-1" aria-hidden="true" tabindex="-1"></a><span class="fu">.libPaths</span>()</span></code></pre></div>
<pre><code>## [1] &quot;C:/Users/jacks/Documents/R/win-library/4.1&quot;
## [2] &quot;C:/Program Files/R/R-4.1.0/library&quot;</code></pre>
<p>Milhares de outras funções, para as mais diversas tarefas, podem ser adicionadas por meio de pacotes (<strong>packages</strong>) disponíveis livremente na internet.<br />
No entanto, a principal fonte de pacotes para o R é o <a href="https://cran.r-project.org/">CRAN</a>, mas também temos <a href="https://r-forge.r-project.org/.">r-forge</a>, <a href="https://github.com/">github</a> e outras fontes pela internet.</p>
<p><a href="https://blog.revolutionanalytics.com/2017/01/cran-10000.html">CRAN now has 10,000 R packages. Here’s how to find the ones you need.</a></p>
<p style="color:red">
<strong>!!!!!!!!!! Não é porque um pacote está no CRAN que ele foi testado e funciona perfeitamente!!!!!!!!!</strong>
</p>
<p><a href="https://cran.r-project.org/web/packages/available_packages_by_name.html">lista de pacotes no CRAN</a></p>
<p>Para instalar um novo pacote, utilize a função <code>install.packages("nome do pacote")</code> ou
<code>Tools-&gt;Install Packages-&gt;Install from  (Repository CRAN) -&gt; Packages (escreva o nome do pacote)</code>.</p>
<p>Para carregar na memória um pacote já instalado, <code>library(nome do pacote)</code> ou <code>require(nome do pacote)</code>.</p>
<p>Ao abrir lista de pacotes vemos quais estão disponíveis. Os que estão marcados estão ativados e disponíveis para uso. Aqueles que não estão marcados podem ser ativados e suas funções utilizadas.</p>
<div class="figure">
<img src="Cap_3_pacotes.png" alt="" />
<p class="caption">lista de pacotes instalados</p>
</div>
<p>Vamos deletar o pacote <code>ggplot2</code>, basta clicar no x no lado direito.
Agora vamos reinstalar pela barra de ferramentas.
Mas o que CRAN quer dizer? É o local onde os pacotes são armazenados.
R é um open source software então se você quiser, pode criar um pacote ar mazená-lo no CRAN.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;analogue&quot;)</span></span>
<span id="cb443-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb443-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(analogue)</span></code></pre></div>
<p>Visite <a href="https://cran.r-project.org/web/packages/analogue/">Analogue</a> e explore o que há disponível para o pacote analogue.
Use a aba packages para explorar suas funcionalidades</p>
<p>Muitas vezes os pacotes disponíveis no <strong>CRAN</strong> não estão <em>UpToDate</em> por isso talvez seja mais interessante isntalar os pacotes diretamente do <a href="https://github.com/">github</a>.</p>
<p>Veja o pacote <a href="https://github.com/trinker/pacman">packman</a> e vamos instalá-lo pelo <strong>github</strong>. Mas antes vamos instalar o pacote <a href="https://www.r-project.org/nosvn/pandoc/devtools.html">devtools</a> que , entre outras coisas, nos permite “buscar” os pacotes do <strong>github</strong>.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb444-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;devtools&quot;)</span></span>
<span id="cb444-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb444-2" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;trinker/pacman&quot;</span>)</span></code></pre></div>
<pre><code>## Skipping install of &#39;pacman&#39; from a github remote, the SHA1 (ace09364) has not changed since last install.
##   Use `force = TRUE` to force installation</code></pre>
<p>Ao utilizar o software R e um pacote na execução de seu trabalho você <strong>deve</strong> citá-los.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span> () <span class="co"># citação do software R</span></span></code></pre></div>
<pre><code>## 
## To cite R in publications use:
## 
##   R Core Team (2021). R: A language and environment for
##   statistical computing. R Foundation for Statistical
##   Computing, Vienna, Austria. URL https://www.R-project.org/.
## 
## A BibTeX entry for LaTeX users is
## 
##   @Manual{,
##     title = {R: A Language and Environment for Statistical Computing},
##     author = {{R Core Team}},
##     organization = {R Foundation for Statistical Computing},
##     address = {Vienna, Austria},
##     year = {2021},
##     url = {https://www.R-project.org/},
##   }
## 
## We have invested a lot of time and effort in creating R, please
## cite it when using it for data analysis. See also
## &#39;citation(&quot;pkgname&quot;)&#39; for citing R packages.</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb448-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="at">package =</span> <span class="st">&quot;analogue&quot;</span>) <span class="co"># citação do pacote Analogue</span></span></code></pre></div>
<pre><code>## 
## To cite use of &#39;analogue&#39; in publications use:
## 
##   Simpson, G.L. and Oksanen, J.  ( 2021 ). analogue: Analogue
##   matching and Modern Analogue Technique transfer function
##   models. (R package version 0.17-6 ).
##   (https://cran.r-project.org/package=analogue).
## 
##   Simpson, G.L. (2007). Analogue Methods in Palaeoecology:
##   Using the analogue Package Journal of Statistical Software,
##   22(2), 1--29
## 
## To see these entries in BibTeX format, use &#39;print(&lt;citation&gt;,
## bibtex=TRUE)&#39;, &#39;toBibtex(.)&#39;, or set
## &#39;options(citation.bibtex.max=999)&#39;.</code></pre>
<p>Aqui listo os pacotes carregados agora em meu R.</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb450-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">.packages</span>())</span></code></pre></div>
<pre><code>##  [1] &quot;analogue&quot;      &quot;vegan&quot;         &quot;lattice&quot;       &quot;permute&quot;      
##  [5] &quot;prob&quot;          &quot;fAsianOptions&quot; &quot;fOptions&quot;      &quot;fBasics&quot;      
##  [9] &quot;timeSeries&quot;    &quot;timeDate&quot;      &quot;combinat&quot;      &quot;magrittr&quot;     
## [13] &quot;ggplot2&quot;       &quot;flow&quot;          &quot;stats&quot;         &quot;graphics&quot;     
## [17] &quot;grDevices&quot;     &quot;utils&quot;         &quot;datasets&quot;      &quot;methods&quot;      
## [21] &quot;base&quot;</code></pre>
<p>Aqui listo os pacotes instalados em meu R.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb452-1" aria-hidden="true" tabindex="-1"></a>meus.pacotes <span class="ot">&lt;-</span> <span class="fu">library</span>()<span class="sc">$</span>results[,<span class="dv">1</span>]</span>
<span id="cb452-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb452-2" aria-hidden="true" tabindex="-1"></a>meus.pacotes</span></code></pre></div>
<pre><code>##   [1] &quot;abind&quot;             &quot;analogue&quot;          &quot;askpass&quot;          
##   [4] &quot;assertthat&quot;        &quot;audio&quot;             &quot;backports&quot;        
##   [7] &quot;base64enc&quot;         &quot;beepr&quot;             &quot;BH&quot;               
##  [10] &quot;bibtex&quot;            &quot;bitops&quot;            &quot;blob&quot;             
##  [13] &quot;blogdown&quot;          &quot;bookdown&quot;          &quot;brew&quot;             
##  [16] &quot;brglm&quot;             &quot;brio&quot;              &quot;broom&quot;            
##  [19] &quot;bslib&quot;             &quot;cachem&quot;            &quot;callr&quot;            
##  [22] &quot;caret&quot;             &quot;cellranger&quot;        &quot;checkmate&quot;        
##  [25] &quot;classInt&quot;          &quot;cli&quot;               &quot;clipr&quot;            
##  [28] &quot;coda&quot;              &quot;colorspace&quot;        &quot;combinat&quot;         
##  [31] &quot;commonmark&quot;        &quot;corrplot&quot;          &quot;cpp11&quot;            
##  [34] &quot;crayon&quot;            &quot;credentials&quot;       &quot;crosstalk&quot;        
##  [37] &quot;crul&quot;              &quot;curl&quot;              &quot;data.table&quot;       
##  [40] &quot;DBI&quot;               &quot;dbplyr&quot;            &quot;decido&quot;           
##  [43] &quot;deldir&quot;            &quot;desc&quot;              &quot;devtools&quot;         
##  [46] &quot;dichromat&quot;         &quot;diffobj&quot;           &quot;digest&quot;           
##  [49] &quot;doParallel&quot;        &quot;dotCall64&quot;         &quot;dplyr&quot;            
##  [52] &quot;dtplyr&quot;            &quot;e1071&quot;             &quot;easyGgplot2&quot;      
##  [55] &quot;ellipsis&quot;          &quot;evaluate&quot;          &quot;expm&quot;             
##  [58] &quot;extraDistr&quot;        &quot;fansi&quot;             &quot;farver&quot;           
##  [61] &quot;fAsianOptions&quot;     &quot;fastmap&quot;           &quot;fBasics&quot;          
##  [64] &quot;fields&quot;            &quot;flow&quot;              &quot;fOptions&quot;         
##  [67] &quot;forcats&quot;           &quot;foreach&quot;           &quot;Formula&quot;          
##  [70] &quot;formula.tools&quot;     &quot;fs&quot;                &quot;gargle&quot;           
##  [73] &quot;gbm&quot;               &quot;gdata&quot;             &quot;generics&quot;         
##  [76] &quot;geobr&quot;             &quot;geojsonsf&quot;         &quot;geometries&quot;       
##  [79] &quot;geosphere&quot;         &quot;gert&quot;              &quot;ggplot2&quot;          
##  [82] &quot;ggrepel&quot;           &quot;ggsci&quot;             &quot;gh&quot;               
##  [85] &quot;gitcreds&quot;          &quot;glcm&quot;              &quot;glue&quot;             
##  [88] &quot;gmodels&quot;           &quot;goftest&quot;           &quot;googledrive&quot;      
##  [91] &quot;googlesheets4&quot;     &quot;gower&quot;             &quot;gridExtra&quot;        
##  [94] &quot;gss&quot;               &quot;gtable&quot;            &quot;gtools&quot;           
##  [97] &quot;haven&quot;             &quot;hexbin&quot;            &quot;highr&quot;            
## [100] &quot;hms&quot;               &quot;htmltools&quot;         &quot;htmlwidgets&quot;      
## [103] &quot;httpcode&quot;          &quot;httpuv&quot;            &quot;httr&quot;             
## [106] &quot;ids&quot;               &quot;igraph&quot;            &quot;ini&quot;              
## [109] &quot;ipred&quot;             &quot;isoband&quot;           &quot;iterators&quot;        
## [112] &quot;jpeg&quot;              &quot;jquerylib&quot;         &quot;jsonify&quot;          
## [115] &quot;jsonlite&quot;          &quot;kableExtra&quot;        &quot;kernlab&quot;          
## [118] &quot;kknn&quot;              &quot;knitr&quot;             &quot;kohonen&quot;          
## [121] &quot;labeling&quot;          &quot;later&quot;             &quot;latticeExtra&quot;     
## [124] &quot;lava&quot;              &quot;lazyeval&quot;          &quot;leafem&quot;           
## [127] &quot;leaflet&quot;           &quot;leaflet.providers&quot; &quot;leafsync&quot;         
## [130] &quot;LearnBayes&quot;        &quot;lifecycle&quot;         &quot;lubridate&quot;        
## [133] &quot;lwgeom&quot;            &quot;magick&quot;            &quot;magrittr&quot;         
## [136] &quot;maps&quot;              &quot;maptree&quot;           &quot;markdown&quot;         
## [139] &quot;memoise&quot;           &quot;metR&quot;              &quot;mime&quot;             
## [142] &quot;miniUI&quot;            &quot;mlbench&quot;           &quot;ModelMetrics&quot;     
## [145] &quot;modelr&quot;            &quot;munsell&quot;           &quot;ncdf4&quot;            
## [148] &quot;NeuralNetTools&quot;    &quot;nomnoml&quot;           &quot;numDeriv&quot;         
## [151] &quot;openssl&quot;           &quot;operator.tools&quot;    &quot;pacman&quot;           
## [154] &quot;permute&quot;           &quot;pillar&quot;            &quot;pkgbuild&quot;         
## [157] &quot;pkgconfig&quot;         &quot;pkgload&quot;           &quot;plyr&quot;             
## [160] &quot;png&quot;               &quot;polyclip&quot;          &quot;praise&quot;           
## [163] &quot;prettyunits&quot;       &quot;princurve&quot;         &quot;prob&quot;             
## [166] &quot;pROC&quot;              &quot;processx&quot;          &quot;prodlim&quot;          
## [169] &quot;profileModel&quot;      &quot;progress&quot;          &quot;progressr&quot;        
## [172] &quot;promises&quot;          &quot;proxy&quot;             &quot;ps&quot;               
## [175] &quot;purrr&quot;             &quot;R.cache&quot;           &quot;R.methodsS3&quot;      
## [178] &quot;R.oo&quot;              &quot;R.utils&quot;           &quot;R6&quot;               
## [181] &quot;randomForest&quot;      &quot;rapidjsonr&quot;        &quot;rappdirs&quot;         
## [184] &quot;raster&quot;            &quot;rasterVis&quot;         &quot;rayimage&quot;         
## [187] &quot;rayrender&quot;         &quot;rayshader&quot;         &quot;rcmdcheck&quot;        
## [190] &quot;RColorBrewer&quot;      &quot;Rcpp&quot;              &quot;RcppArmadillo&quot;    
## [193] &quot;RcppThread&quot;        &quot;RCurl&quot;             &quot;readr&quot;            
## [196] &quot;readxl&quot;            &quot;recipes&quot;           &quot;rematch&quot;          
## [199] &quot;rematch2&quot;          &quot;remotes&quot;           &quot;reprex&quot;           
## [202] &quot;reshape&quot;           &quot;reshape2&quot;          &quot;rgdal&quot;            
## [205] &quot;rgeos&quot;             &quot;rgl&quot;               &quot;rlang&quot;            
## [208] &quot;rmarkdown&quot;         &quot;rnaturalearth&quot;     &quot;rnaturalearthdata&quot;
## [211] &quot;RNCEP&quot;             &quot;roxygen2&quot;          &quot;rpart.plot&quot;       
## [214] &quot;rprojroot&quot;         &quot;RStoolbox&quot;         &quot;rstudioapi&quot;       
## [217] &quot;rversions&quot;         &quot;rvest&quot;             &quot;sass&quot;             
## [220] &quot;scales&quot;            &quot;selectr&quot;           &quot;servr&quot;            
## [223] &quot;sessioninfo&quot;       &quot;sf&quot;                &quot;sfheaders&quot;        
## [226] &quot;shiny&quot;             &quot;sourcetools&quot;       &quot;sp&quot;               
## [229] &quot;spacefillr&quot;        &quot;spam&quot;              &quot;spatialEco&quot;       
## [232] &quot;spatstat.core&quot;     &quot;spatstat.data&quot;     &quot;spatstat.geom&quot;    
## [235] &quot;spatstat.sparse&quot;   &quot;spatstat.utils&quot;    &quot;spData&quot;           
## [238] &quot;spdep&quot;             &quot;SQUAREM&quot;           &quot;stabledist&quot;       
## [241] &quot;stars&quot;             &quot;stringi&quot;           &quot;stringr&quot;          
## [244] &quot;styler&quot;            &quot;svglite&quot;           &quot;synoptReg&quot;        
## [247] &quot;sys&quot;               &quot;systemfonts&quot;       &quot;tensor&quot;           
## [250] &quot;terra&quot;             &quot;terrainmeshr&quot;      &quot;testthat&quot;         
## [253] &quot;tgp&quot;               &quot;tibble&quot;            &quot;tidyr&quot;            
## [256] &quot;tidyselect&quot;        &quot;tidyverse&quot;         &quot;timeDate&quot;         
## [259] &quot;timeSeries&quot;        &quot;tinytex&quot;           &quot;tmap&quot;             
## [262] &quot;tmaptools&quot;         &quot;trend&quot;             &quot;triebeard&quot;        
## [265] &quot;units&quot;             &quot;urltools&quot;          &quot;usethis&quot;          
## [268] &quot;utf8&quot;              &quot;uuid&quot;              &quot;vctrs&quot;            
## [271] &quot;vegan&quot;             &quot;viridis&quot;           &quot;viridisLite&quot;      
## [274] &quot;waldo&quot;             &quot;webshot&quot;           &quot;wesanderson&quot;      
## [277] &quot;whisker&quot;           &quot;widgetframe&quot;       &quot;withr&quot;            
## [280] &quot;xfun&quot;              &quot;XML&quot;               &quot;xml2&quot;             
## [283] &quot;xopen&quot;             &quot;xtable&quot;            &quot;yaml&quot;             
## [286] &quot;zip&quot;               &quot;zoo&quot;               &quot;base&quot;             
## [289] &quot;boot&quot;              &quot;class&quot;             &quot;cluster&quot;          
## [292] &quot;codetools&quot;         &quot;compiler&quot;          &quot;datasets&quot;         
## [295] &quot;foreign&quot;           &quot;graphics&quot;          &quot;grDevices&quot;        
## [298] &quot;grid&quot;              &quot;KernSmooth&quot;        &quot;lattice&quot;          
## [301] &quot;MASS&quot;              &quot;Matrix&quot;            &quot;methods&quot;          
## [304] &quot;mgcv&quot;              &quot;nlme&quot;              &quot;nnet&quot;             
## [307] &quot;parallel&quot;          &quot;rpart&quot;             &quot;spatial&quot;          
## [310] &quot;splines&quot;           &quot;stats&quot;             &quot;stats4&quot;           
## [313] &quot;survival&quot;          &quot;tcltk&quot;             &quot;tools&quot;            
## [316] &quot;translations&quot;      &quot;utils&quot;</code></pre>
<p>Ou poderia simplesmente digitar <code>library()</code>.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb454-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>()</span></code></pre></div>
</div>
</div>
<div id="entrando-com-dados" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Entrando com dados</h2>
<p>Agora que dominamos <del>100%</del> as estruturas e tratamento de objetos podemos partir para importação de dados das mais variadas fontes.<br />
Até agora nós basicamente trabalhamos com dados “<code>café com leite</code>.” Criamos uma tabelinha aqui, uma matrizinha acolá um vetor e por aí vai.<br />
Sinto muito em informá-los, mas o mundo é bem mais complexo e cruel.</p>
<table>
<colgroup>
<col width="100%" />
</colgroup>
<tbody>
<tr class="odd">
<td><em>“O mundo não é um mar de rosas. É um lugar sujo, um lugar cruel, que não quer saber o quanto você é durão. Vai botar você de joelhos e você vai ficar de joelhos para sempre se você deixar. Você, eu, ninguém vai bater tão forte como a vida, mas não se trata de bater forte. Se trata de quanto você aguenta apanhar e seguir em frente, o quanto você é capaz de aguentar e continuar tentando. É assim que se consegue vencer.Agora se você sabe do teu valor, então vá atrás do que você merece, mas tem que estar preparado para apanhar. E nada de apontar dedos, dizer que você não consegue por causa dele ou dela, ou de quem quer que seja. Só covardes fazem isso e você não é covarde, você é melhor que isso.”</em></td>
</tr>
</tbody>
</table>
<p><strong>Balboa, Rocky</strong>
|</p>
<p>Os dados no R podem ser importados por diferentes meios (teclado, text file, outros softwares estatísticos, planilhas e etc).</p>
<p><img src="Cap_3_data%20input.png" id="id" class="class" style="width:50.0%;height:50.0%" alt="Data input" /><br />
Fonte: <span class="citation"><a href="#ref-Kabacoff2015R" role="doc-biblioref">Kabacoff</a> (<a href="#ref-Kabacoff2015R" role="doc-biblioref">2015</a>)</span></p>
<div id="edit" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> edit()</h3>
<p>A forma mais simples de inserção de dados é através do teclado.
No caso a seguir, o comando <code>Matrícula=numeric(0)</code> cria uma variável de um <code>mode()</code>específico, mas sem dados. O comando <code>edit()</code>, por sua vez, e como nome sugere, permite editar um banco de dados. Um <em>popup</em> abrirá na sua tela que permitirá a sua edição. Após o uso bas fechar que as edições feitas serão salvas.</p>
<div class="figure">
<img src="Cap_3_edit%20DF.JPG" id="id" class="class" style="width:35.0%;height:35.0%" alt="" />
<p class="caption"><strong>comando edit()</strong></p>
</div>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb455-1" aria-hidden="true" tabindex="-1"></a>Alunos.Eng792 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Nome=</span><span class="fu">character</span>(<span class="dv">0</span>),Matrícula<span class="ot">=</span><span class="fu">numeric</span>(<span class="dv">0</span>), Curço<span class="ot">=</span><span class="fu">character</span>(<span class="dv">0</span>),Nível<span class="at">.de.R=</span><span class="fu">numeric</span>(<span class="dv">0</span>),Nível.de.Pós<span class="ot">=</span><span class="fu">character</span>(<span class="dv">0</span>))</span>
<span id="cb455-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb455-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb455-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb455-3" aria-hidden="true" tabindex="-1"></a>Alunos.Eng792</span></code></pre></div>
<pre><code>## [1] Nome         Matrícula    Curço        Nível.de.R   Nível.de.Pós
## &lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb457-1" aria-hidden="true" tabindex="-1"></a>Alunos.Eng792 <span class="ot">&lt;-</span> <span class="fu">edit</span>(Alunos.Eng792)</span>
<span id="cb457-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb457-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb457-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb457-3" aria-hidden="true" tabindex="-1"></a>Alunos.Eng792</span></code></pre></div>
<pre><code>## [1] Nome         Matrícula    Curço        Nível.de.R   Nível.de.Pós
## &lt;0 linhas&gt; (ou row.names de comprimento 0)</code></pre>
</div>
<div id="built-in" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> built-in</h3>
<p>No R também temos os dados <em>buit-in</em> que são dados que já vem “dentro” do R ou pacotes que permite a execução dos exemplos das funções naturais do R e aquelas instaladas por meio dos pacotes. Temos vários dados <em>built-in</em> no R como <code>ìris</code>, <code>mtcars</code>, <code>anscombe</code>, <code>USArrests</code>, <code>USAccDeaths</code>,<code>AirPassengers</code> e etc.</p>
<p>Vamos dar uma olha no <code>USArrests</code> que contém estatísticas de presos por diferentes crimes em EUA em taxas de 100.000.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb459-1" aria-hidden="true" tabindex="-1"></a>Presidiarios.USA<span class="ot">&lt;-</span>(USArrests)</span>
<span id="cb459-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb459-2" aria-hidden="true" tabindex="-1"></a>Presidiarios.USA</span></code></pre></div>
<pre><code>##                Murder Assault UrbanPop Rape
## Alabama          13.2     236       58 21.2
## Alaska           10.0     263       48 44.5
## Arizona           8.1     294       80 31.0
## Arkansas          8.8     190       50 19.5
## California        9.0     276       91 40.6
## Colorado          7.9     204       78 38.7
## Connecticut       3.3     110       77 11.1
## Delaware          5.9     238       72 15.8
## Florida          15.4     335       80 31.9
## Georgia          17.4     211       60 25.8
## Hawaii            5.3      46       83 20.2
## Idaho             2.6     120       54 14.2
## Illinois         10.4     249       83 24.0
## Indiana           7.2     113       65 21.0
## Iowa              2.2      56       57 11.3
## Kansas            6.0     115       66 18.0
## Kentucky          9.7     109       52 16.3
## Louisiana        15.4     249       66 22.2
## Maine             2.1      83       51  7.8
## Maryland         11.3     300       67 27.8
## Massachusetts     4.4     149       85 16.3
## Michigan         12.1     255       74 35.1
## Minnesota         2.7      72       66 14.9
## Mississippi      16.1     259       44 17.1
## Missouri          9.0     178       70 28.2
## Montana           6.0     109       53 16.4
## Nebraska          4.3     102       62 16.5
## Nevada           12.2     252       81 46.0
## New Hampshire     2.1      57       56  9.5
## New Jersey        7.4     159       89 18.8
## New Mexico       11.4     285       70 32.1
## New York         11.1     254       86 26.1
## North Carolina   13.0     337       45 16.1
## North Dakota      0.8      45       44  7.3
## Ohio              7.3     120       75 21.4
## Oklahoma          6.6     151       68 20.0
## Oregon            4.9     159       67 29.3
## Pennsylvania      6.3     106       72 14.9
## Rhode Island      3.4     174       87  8.3
## South Carolina   14.4     279       48 22.5
## South Dakota      3.8      86       45 12.8
## Tennessee        13.2     188       59 26.9
## Texas            12.7     201       80 25.5
## Utah              3.2     120       80 22.9
## Vermont           2.2      48       32 11.2
## Virginia          8.5     156       63 20.7
## Washington        4.0     145       73 26.2
## West Virginia     5.7      81       39  9.3
## Wisconsin         2.6      53       66 10.8
## Wyoming           6.8     161       60 15.6</code></pre>
</div>
<div id="scan" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> scan()</h3>
<p>Uma outra forma de entrada manual se dá através dom comando <code>scan()</code>. Neste formato de entrada de dados podemos digitar informação por informação ou copiar de uma fonte e colá-la. Tudo isso feito no console e em formato numérico.</p>
<p><strong>Exemplo com digitação.</strong></p>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb461-1" aria-hidden="true" tabindex="-1"></a>teste1 <span class="ot">&lt;-</span><span class="fu">scan</span>()</span>
<span id="cb461-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb461-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Digite 1, 2, 4, 5, 6, 7, 8</span></span>
<span id="cb461-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb461-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb461-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb461-4" aria-hidden="true" tabindex="-1"></a>teste1</span></code></pre></div>
<p><strong>Exemplo com copia e cola.</strong></p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">30</span>,<span class="dv">38</span>)</span>
<span id="cb462-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb462-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb462-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb462-3" aria-hidden="true" tabindex="-1"></a>teste2 <span class="ot">&lt;-</span><span class="fu">scan</span>()</span>
<span id="cb462-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb462-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb462-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb462-5" aria-hidden="true" tabindex="-1"></a>teste2</span></code></pre></div>
</div>
<div id="lendo-arquivos-de-texto-.txt" class="section level3" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> Lendo arquivos de texto (.txt)</h3>
<p>No dia a dia esbarramos em dados que estão disponíveis em formato de texto. Geralmente este dados estão organizados em linhas e colunas onde cada linha representa uma observação e cada coluna uma variável.</p>
<p>Para fazer leitura de dados em formato de texto (<strong>.txt</strong>) podemos utilizar o comando <code>read.table()</code> que lê o arquivo em formato de tabela e armazena em formato de <em>data.frame</em>.</p>
<p>A sintaxe do comando é:<br />
<code>meu.df &lt;- read.table(file, options)</code></p>
<p>Existem muitas opções ( <em>options</em>) disponíveis, mas podemos destacar algumas mais utilizadas <code>header</code>, <code>sep</code>, <code>row.names</code>, <code>col.names</code>, <code>skip</code>.</p>
<p>Para saber quais são as <em>options</em> e o que cada uma delas faz você pode acessar através de <code>?data.datble</code>.</p>
<p>No caso abaixo estamos utilizando <code>sep=","</code>, <code>header=T</code> e <code>skip=3</code>.</p>
<p>Baixe os dados aqui <strong>Cap_3_Notas_ENG792.txt</strong> no <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb463-1" aria-hidden="true" tabindex="-1"></a>notas<span class="ot">&lt;-</span><span class="fu">read.table</span>(<span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Notas_ENG792.txt&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>, <span class="at">header =</span> T, <span class="at">skip=</span><span class="dv">3</span>)</span>
<span id="cb463-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb463-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb463-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb463-3" aria-hidden="true" tabindex="-1"></a>notas</span></code></pre></div>
<pre><code>##    Nome Nota.1 Nota.2 Nota.3 Nota.4
## 1     A   10.9   60.9   53.6   12.0
## 2     B   71.3    9.9   13.9   47.0
## 3     C   65.9    0.3   28.9   55.0
## 4     D    3.6   70.0   37.9   75.3
## 5     E   70.9   81.9   43.9    8.6
## 6     F   76.9   53.0   29.9   38.6
## 7     G   73.6    2.3   23.0   37.3
## 8     H    2.0   88.0   10.3   28.3
## 9     I   25.3   11.9   12.3   26.3
## 10    J    7.0   19.3   82.9   46.3
## 11    K   52.0   41.0   70.3   31.6
## 12    L   27.3   74.0   47.6   18.9
## 13    M   87.9   75.9   17.9   80.6
## 14    N   76.0   47.9    2.0   19.6
## 15    O   55.0   60.6   51.9   24.0
## 16    P   76.6   47.9   90.3   55.6
## 17    Q   10.3   55.9   18.0   86.3
## 18    R   17.0    0.9   43.3   14.6
## 19    S   38.6   22.6   23.6    6.6
## 20    T   69.0   31.9   75.3   90.6
## 21    U   26.9    3.6   65.3   48.6
## 22    X   56.6   32.0   74.6   28.0
## 23    Y   22.3   42.3   88.9   65.0
## 24    Z   36.6   44.3   17.9   23.9</code></pre>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(notas)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  5 variables:
##  $ Nome  : chr  &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; ...
##  $ Nota.1: num  10.9 71.3 65.9 3.6 70.9 76.9 73.6 2 25.3 7 ...
##  $ Nota.2: num  60.9 9.9 0.3 70 81.9 53 2.3 88 11.9 19.3 ...
##  $ Nota.3: num  53.6 13.9 28.9 37.9 43.9 29.9 23 10.3 12.3 82.9 ...
##  $ Nota.4: num  12 47 55 75.3 8.6 38.6 37.3 28.3 26.3 46.3 ...</code></pre>
<p>Acima nós criamos o objeto <code>notas</code>pela importação do arquivo <code>Notas_ENG792.txt</code> referente às notas hipotéticas de vocês na disciplina Eng 792 ao término do semestre.<br />
Este arquivo está armazenado em meu computador na pasta <code>J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/</code>. Preste atenção na forma como ele foi importado o endereço veio antes do nome do arquivo e as separações entre os diretórios se pelo uso de <code>/</code>, mas também poderia ter utilizado <code>\\</code>.<br />
Após o endereço do arquivo vieram as <em>options</em> separadas por vírgulas (<code>,</code>). Se você tiver a curiosidade de abrir o arquivo <code>.txt</code>, você verá como os dados estão organizados e entenderá a utilização de cada argumento.</p>
<p>No entanto, como eu sou gente boa, vou ajudar vocês embora vocês não mereçam.</p>
<p>O argumento <code>sep=","</code>foi utilizado pois os dados de cada “célula” está separado da outra por meio de uma vírgula <code>,</code>.</p>
<p><code>sep=""</code> indica <em>espaço</em> delimitando os dados
<code>sep="\t"</code> indica <em>tab</em> delimitando os dados
<code>sep="\n"</code> indica <em>new line</em> delimitaNdo os dados</p>
<p>O argumento <code>header=T"</code> indica que nossa tabela tem cabeçalho e é a primeira linha após o <code>skip=3</code>.</p>
<p>O argumento <code>skip=3"</code> indica que as 3 primeiras linhas de nosso arquivo devem ser ignoradas começando assim, nossa tabela a partir da 4ª linha.</p>
<p>Note ainda que os nomes das colunas foram automaticamente alterados para atender as convenções de condificação do R. Onde originalmente estava <em>Nota 1</em> agora temos <em>Nota.1</em>.</p>
<div class="figure">
<img src="Cap_3_notas%20eng%20792.jpg" alt="" />
<p class="caption"><strong>Notas Eng792</strong></p>
</div>
Vejam que na tabela criada houve erros na na codificação dos caracteres especiais.
<p style="color:red">
<strong>RESOLVA ISSO! E digo mais determine que a primeira coluna (os nomes de vocês) sejam o nome das linhas</strong>
</p>
</div>
<div id="read.csv" class="section level3" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> read.csv()</h3>
<p>Embora muito comuns arquivos em formato <code>.txt</code>, a maioria dos cientistas preferem armazenar dados em planilhas eletrônicas como do excel <code>xlsx.</code> ou <code>.csv</code> ( <em>comma-separated values</em>).</p>
<p>Baixe o arquivo <strong>Cap_1_P2-Mispriced-Diamonds.csv</strong> <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb467-1" aria-hidden="true" tabindex="-1"></a>diamantes<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_1_P2-Mispriced-Diamonds.csv&quot;</span>)</span>
<span id="cb467-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb467-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb467-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb467-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(diamantes)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    53940 obs. of  3 variables:
##  $ carat  : num  0.23 0.21 0.23 0.29 0.31 0.24 0.24 0.26 0.22 0.23 ...
##  $ clarity: chr  &quot;SI2&quot; &quot;SI1&quot; &quot;VS1&quot; &quot;VS2&quot; ...
##  $ price  : int  326 326 327 334 335 336 336 337 337 338 ...</code></pre>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb469-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diamantes) <span class="co"># mostra as 6 primeiras linhas do objeto</span></span></code></pre></div>
<pre><code>##   carat clarity price
## 1  0.23     SI2   326
## 2  0.21     SI1   326
## 3  0.23     VS1   327
## 4  0.29     VS2   334
## 5  0.31     SI2   335
## 6  0.24    VVS2   336</code></pre>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb471-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(diamantes) <span class="co"># mostra as 6 últimas linhas do objeto </span></span></code></pre></div>
<pre><code>##       carat clarity price
## 53935  0.72     SI1  2757
## 53936  0.72     SI1  2757
## 53937  0.72     SI1  2757
## 53938  0.70     SI1  2757
## 53939  0.86     SI2  2757
## 53940  0.75     SI2  2757</code></pre>
<p>Observem que no comando <code>read.csv()</code> nós não adicionamos o argumento <code>header=T</code>, issto por que por padrão <code>header</code>é igual a <code>TRUE (T)</code>, caso seus dados não tenham cabeçalhos você deve argumentar <code>header=F</code></p>
<p>Você já deve ter esbarrado com dados no “brasileiros” nos quais os separadores decimais não são pontos como no padrão internacional, mas vírgulas. Da mesma maneira, em Banânia, os separadores de de células são <em>ponto e vírgula</em> (<em>semi-vírgula - ;</em>).</p>
<p>Para evitar problemas como esse na importação dos dados, (<span class="citation"><a href="#ref-perlin2018processamento" role="doc-biblioref">Perlin</a> (<a href="#ref-perlin2018processamento" role="doc-biblioref">2018</a>)</span>) sugere que sejam abertos em um editor de texto qualquer e substitua todos os valores de <em>vírgula (,)</em> por <em>ponto (.)</em>. Isso deixa o arquivo em um formato internacional. No Windows, programas como o Notepad e o Notepad + + realizam essa tarefa facilmente, no linux o <em>gedit</em> e etc.</p>
<p><span class="citation"><a href="#ref-perlin2018processamento" role="doc-biblioref">Perlin</a> (<a href="#ref-perlin2018processamento" role="doc-biblioref">2018</a>)</span> suegre para evitar problemas, antes de prosseguir para a importação de dados em um arquivo <em>.csv</em>, deve-se abrir o arquivo em um editor de texto qualquer e verificar:</p>
<ol style="list-style-type: decimal">
<li>A existência de texto antes dos dados e a necessidade de ignorar algumas linhas iniciais;</li>
<li>A existência ou não dos nomes das colunas;</li>
<li>O símbolo separador de colunas;</li>
<li>O símbolo de decimal, o qual deve ser o ponto (.).</li>
</ol>
<p>Caso não seja possível converter os dados para o formato internacional, para esta jaboticaba você pode utilizar funções específicas como <code>read.csv2()</code> que assume que o indicador de decimal é a <em>vírgula (,)</em> e o separação de colunas é o <em>ponto-e-vírgula (;)</em>.</p>
<p>O <code>read.csv()</code>usa como <em>default</em> o padrão internacional <code>sep=”,”</code> e <code>dec=”.”</code> já o <code>read.csv2()</code> tem por default o padrão <code>sep=";"</code> e <code>dec=","</code>.<br />
<code>dec=""</code> (separador de casas decimais)</p>
<p>Experimente ambos comandos para abrir o <em>Notas_ENG792.csv</em>.<br />
![**Notas_,_.csvCap_3_notas.csv eng 792.jpg:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3){#id .class width=50% height=50%}</p>
<p>Temos 1 arquivo <strong>Cap_3_Notas_ENG792.csv</strong> <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb473-1" aria-hidden="true" tabindex="-1"></a>Notas.csv<span class="ot">&lt;-</span><span class="fu">read.csv2</span>(<span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Notas_ENG792.csv&quot;</span>, <span class="at">row.names =</span> <span class="st">&quot;Nome&quot;</span>)</span>
<span id="cb473-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb473-2" aria-hidden="true" tabindex="-1"></a>Notas.csv</span></code></pre></div>
<pre><code>##   Nota.1 Nota.2 Nota.3 Nota.4
## A   10.9   60.9   53.6   12.0
## B   71.3    9.9   13.9   47.0
## C   65.9    0.3   28.9   55.0
## D    3.6   70.0   37.9   75.3
## E   70.9   81.9   43.9    8.6
## F   76.9   53.0   29.9   38.6
## G   73.6    2.3   23.0   37.3
## H    2.0   88.0   10.3   28.3
## I   25.3   11.9   12.3   26.3
## J    7.0   19.3   82.9   46.3
## K   52.0   41.0   70.3   31.6
## L   27.3   74.0   47.6   18.9
## M   87.9   75.9   17.9   80.6
## N   76.0   47.9    2.0   19.6
## O   55.0   60.6   51.9   24.0
## P   76.6   47.9   90.3   55.6
## Q   10.3   55.9   18.0   86.3
## R   17.0    0.9   43.3   14.6
## S   38.6   22.6   23.6    6.6
## T   69.0   31.9   75.3   90.6
## U   26.9    3.6   65.3   48.6
## V   56.6   32.0   74.6   28.0
## X   22.3   42.3   88.9   65.0
## Y   36.6   44.3   17.9   23.9
## Z   40.0   65.0   77.9   59.0</code></pre>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb475-1" aria-hidden="true" tabindex="-1"></a>Notas.csv<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Notas_ENG792.csv&quot;</span>, <span class="at">row.names =</span> <span class="st">&quot;Nome&quot;</span>)</span></code></pre></div>
<pre><code>## Error in read.table(file = file, header = header, sep = sep, quote = quote, : more columns than column names</code></pre>
<p style="color:red">
<strong>Note que o comando <code>read.csv()</code> não funcionou, faça os ajustes necessários para que ele funcine.</strong>
</p>
<p>Explore o comandos <code>rowSums()</code>, <code>colSums()</code>, <code>rowMeans()</code>, <code>colMeans()</code>.</p>
</div>
<div id="planilhas-excel-completas-.xls-ou-.xlsx" class="section level3" number="4.3.6">
<h3><span class="header-section-number">4.3.6</span> Planilhas excel completas (.xls ou .xlsx)</h3>
<p>É muito comum encontrarmos dados organizados em diferentes planilhas dentro de um mesmo arquivo como no caso do excel ( <em>.xls</em> ou <em>.xlsx</em>) e semelehantes ( <em>.odt</em>).</p>
<p>Estes arquivos e suas diferentes abas podem ser acessados pelo R também, no entanto não há funções nativas que executem esta ação. Precisamos nesse caso instalar pacotes de funções específicas para desempnhar esta operação.</p>
<p>Temos algumas opções de pacotes para esta função como <code>XLConnect</code> (<span class="citation"><a href="#ref-MiraiSolutionsGmbH2020" role="doc-biblioref">Mirai Solutions GmbH</a> (<a href="#ref-MiraiSolutionsGmbH2020" role="doc-biblioref">2020</a>)</span>), <code>xlsx</code> (<span class="citation"><a href="#ref-DragulescuandArendt2007" role="doc-biblioref">Dragulescu and Arendt</a> (<a href="#ref-DragulescuandArendt2007" role="doc-biblioref">2020</a>)</span>) e <code>readxl</code> (<span class="citation"><a href="#ref-WickhamandBryan2019" role="doc-biblioref">Wickham and Bryan</a> (<a href="#ref-WickhamandBryan2019" role="doc-biblioref">2019</a>)</span>).</p>
<p>Caso a instalação desses pacotes não funcione e, a mensagem de abaixo apareça.</p>
<p><code>error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.</code></p>
<p>Experimente instalar ou atualizar antes o <a href="https://www.java.com/en/download/manual.jsp"><em>Java</em></a> correspondente ao seu sistema operacional e <em>bit</em>.</p>
<p>Vamos abrir o <em>Definições iniciais - ENG 792.xlsx</em>.<br />
<img src="J:/ENG%20792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_InformaÃ§Ãµes%20-%20Alunos%20ENG%20792.jpg" id="id" class="class" style="width:100.0%;height:100.0%" alt="Informações Alunos - ENG 792.xlsx" /></p>
<p>Eu já tenho instalado no meu <strong>R</strong>, então instale no seu caso não o tenha.
<code>install.packages("xlsx")</code></p>
<p>Baixe os dados aqui
Baixe o arquivo <strong>Cap_3_Informações - Alunos ENG 792.xlsx</strong> <a href="https://www2.cead.ufv.br/sistemas/pvanet/geral/login.php">PVANet</a></p>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb477-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(xlsx)</span>
<span id="cb477-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb477-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb477-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb477-3" aria-hidden="true" tabindex="-1"></a>Info.Alunos<span class="ot">&lt;-</span><span class="fu">read.xlsx</span>(<span class="at">file=</span><span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.xlsx&quot;</span>, <span class="at">endRow=</span><span class="dv">28</span>,<span class="at">sheetIndex=</span><span class="dv">4</span>,<span class="at">startRow =</span> <span class="dv">2</span>, <span class="at">header =</span> T,<span class="at">encoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span>
<span id="cb477-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb477-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb477-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb477-5" aria-hidden="true" tabindex="-1"></a>Info.Alunos</span></code></pre></div>
</div>
<div id="exportar-arquivos" class="section level3" number="4.3.7">
<h3><span class="header-section-number">4.3.7</span> Exportar arquivos()</h3>
<p>Uma vez que somo capazes de importar arquivos de formatos específicos, somo também capazes de exportá-los.</p>
<p>Podemos exportar <code>data.frame</code>, <code>matrix</code> ou <code>vector</code> para <code>.csv</code> (dos 2 tipos <code>csv</code> e <code>csv2</code>) e para <code>.txt</code>.</p>
<p>A estrutura é semelhante para diferentes métodos (<code>write.csv()</code>, <code>write.csv2()</code> ou <code>write.table()</code>):</p>
<p><code>write.csv(Objeto, file = “objeto.csv", append = FALSE, quote = TRUE, sep = " ", eol = "\n",</code>
<code>na = "NA", dec = ".", row.names = TRUE, col.names = TRUE, qmethod = c("escape", "double"), fileEncoding = "")</code></p>
<p>Vamos experimentar os diferentes comandos.
Antes de prosseguir certifique-se que o endereço de saída está adequado.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb478-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(Info.Alunos, <span class="at">file=</span><span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.csv&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>,<span class="at">fileEncoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in write.csv(Info.Alunos, file = &quot;J:/ENG 792/ENG_792-AVDR/
## ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.csv&quot;, : attempt to set
## &#39;sep&#39; ignored</code></pre>
<pre><code>## Error in is.data.frame(x): object &#39;Info.Alunos&#39; not found</code></pre>
<div class="sourceCode" id="cb481"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb481-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb481-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv2</span>(Info.Alunos, <span class="at">file=</span><span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.2.csv&quot;</span>,<span class="at">sep=</span><span class="st">&quot;,&quot;</span>,<span class="at">fileEncoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in write.csv2(Info.Alunos, file = &quot;J:/ENG 792/ENG_792-AVDR/
## ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.2.csv&quot;, : attempt to set
## &#39;sep&#39; ignored</code></pre>
<pre><code>## Error in is.data.frame(x): object &#39;Info.Alunos&#39; not found</code></pre>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(Info.Alunos, <span class="at">file=</span><span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/Cap_3_Informações - Alunos ENG 792.txt&quot;</span>, <span class="at">sep=</span><span class="st">&quot;,&quot;</span>,<span class="at">fileEncoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span></code></pre></div>
<pre><code>## Error in is.data.frame(x): object &#39;Info.Alunos&#39; not found</code></pre>
</div>
<div id="definir-diretório-de-trabalho-setwd" class="section level3" number="4.3.8">
<h3><span class="header-section-number">4.3.8</span> Definir diretório de trabalho <code>setwd()</code></h3>
<p>Durante a importação e exportação de dados nós forncemos dentro dos comandos os endereço no seu computador ou periférico de onde e para onde os dados deveriam ser importados e exportados, respectivamente.</p>
<p>Esta tarefa pode ser simplificada pela determinação de um diretório de trabalho. Após esta definição o R vai comunicar diretamente com esta pasta de maneira que todos os arquivos importados e exportados de a para esta pasta.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb486-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;J:/ENG 792/ENG_792-AVDR/ENG.792-AVDR/&quot;</span>)</span>
<span id="cb486-2"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb486-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb486-3"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb486-3" aria-hidden="true" tabindex="-1"></a>Reposição.de.aula<span class="ot">&lt;-</span><span class="fu">read.xlsx</span>(<span class="at">file=</span><span class="st">&quot;Cap_3_Informações - Alunos ENG 792.xlsx&quot;</span>, <span class="at">endRow=</span><span class="dv">28</span>,<span class="at">sheetIndex=</span><span class="dv">4</span>,<span class="at">startRow =</span> <span class="dv">2</span>, <span class="at">header =</span>T, <span class="at">encoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span>
<span id="cb486-4"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb486-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb486-5"><a href="acessando-e-criando-funções-importação-e-exportação-dados.html#cb486-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(Reposição.de.aula, <span class="at">file=</span><span class="st">&quot;Cap_3_Informações - Alunos ENG 792.txt&quot;</span>,<span class="at">sep=</span><span class="st">&quot;,&quot;</span>,<span class="at">fileEncoding=</span><span class="st">&quot;UTF-8&quot;</span>)</span></code></pre></div>
<p style="color:red">
<strong>Explore o comandos <code>rowSums()</code>, <code>colSums()</code>, <code>rowMeans()</code>, <code>colMeans()</code> e acrescente no <em>data.frame</em> notas uma coluna com soma e média das notas dos alunos e linhas com no fim do arquivo soma e média das notas 1 a 4. Para terminar exporte os arquivos em formato .csv e .txt</strong>
</p>
<p><strong>Para mais informações sobre importação e exportação de dados leia</strong> <span class="citation"><a href="#ref-RCoreTeam" role="doc-biblioref">RCoreTeam</a> (<a href="#ref-RCoreTeam" role="doc-biblioref">2020</a>)</span> <strong>.</strong></p>
<p style="color:red">
<strong>E digo mais, é só isso mesmo.</strong>
</p>
</div>
<div id="exercícios-1" class="section level3" number="4.3.9">
<h3><span class="header-section-number">4.3.9</span> Exercícios</h3>
<ol style="list-style-type: decimal">
<li>Defina um objeto chamado a com valores de 60 a 85.</li>
<li>Determine o elemento 12 de a.</li>
<li>Determine elemento 20 de a.</li>
<li>Mostre o 5° e 25° elementos de a.</li>
<li>Mostre o 4°, 8°, 12°, 20° e 24° elementos de a.</li>
<li>Mostre todos exceto 18°elemento de a.</li>
<li>Mostre todos exceto o 2°, 15° e 17° elementos de a .</li>
<li>Gere um data frame chamado new_frame com 3 colunas: A primeira com valores de 33 a 47; a segunda começando em 115 e terminando em 157, com incrementos de 3; e a terceira começando em 10, com 15 elementods, e cada elemento decrescendo 8.5. Cada coluna deve ser chamada de X, Y e Z respectivamente.</li>
<li>Extraia todos os valores da coluna 1.</li>
<li>Extraia das linhas 6 a 10 da coluna 2.</li>
<li>Extraia os valores da linha 11 para todas as colunas.</li>
<li>Extraia os valores das linhas 4 a 8 das colunas 1 e 3 em formato de data frame</li>
<li>Demonstre como mostrar o número de linhas do new_frame.</li>
<li>Demonstre 4 diferentes métodos de extrair os valores de todas as linhas da coluna 1 de new_frame.</li>
</ol>
</div>
</div>
<div id="dica-de-leitura-1" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Dica de leitura</h2>
<p><a href="https://statisticsglobe.com/pacman-r-package">Introduction to the pacman Package in R (3 Examples)</a></p>

<div id="refs" class="references csl-bib-body hanging-indent">
<div class="csl-entry">
Dragulescu, Adrian, and Cole Arendt. 2020. <em>Xlsx: Read, Write, Format Excel 2007 and Excel 97/2000/XP/2003 Files</em>. <a href="https://CRAN.R-project.org/package=xlsx">https://CRAN.R-project.org/package=xlsx</a>.
</div>
<div class="csl-entry">
Freire, S. M. 2020. <em>Introdução Ao r</em>. bookdown. <a href="https://bookdown.org/steve_midway/DAR/">https://bookdown.org/steve_midway/DAR/</a>.
</div>
<div class="csl-entry">
Kabacoff, Robert I. 2015. <em><span class="nocase">R in Action</span></em>. Second. Manning. <a href="http://www.worldcat.org/isbn/9781617291388">http://www.worldcat.org/isbn/9781617291388</a>.
</div>
<div class="csl-entry">
Meireles, Fernando, and Denisson Silva. 2018. <em>Usando r: Um Guia Para Cientistas Políticos</em>. bookdown. <a href="http://electionsbr.com/livro/index.html">http://electionsbr.com/livro/index.html</a>.
</div>
<div class="csl-entry">
Mello, M. P., and L. A. Peternelli. 2013. <em>Conhecendo o r: Uma Visão Mais Que Estatística</em>. First. Editora UFV.
</div>
<div class="csl-entry">
Mirai Solutions GmbH. 2020. <em>XLConnect: Excel Connector for r</em>. <a href="https://CRAN.R-project.org/package=XLConnect">https://CRAN.R-project.org/package=XLConnect</a>.
</div>
<div class="csl-entry">
Neth, H. 2021. <em>Data Science for Psychologists</em>. bookdown. <a href="https://bookdown.org/hneth/ds4psy/">https://bookdown.org/hneth/ds4psy/</a>.
</div>
<div class="csl-entry">
Peng, R. D. 2020. <em>R Programming for Data Science</em>. bookdown. <a href="https://bookdown.org/rdpeng/rprogdatascience/">https://bookdown.org/rdpeng/rprogdatascience/</a>.
</div>
<div class="csl-entry">
Perlin, M. S. 2018. <em>Processamento e an<span>á</span>lise de Dados Financeiros e Econ<span>ô</span>micos Com o r</em>. Cl<span>ó</span>vis Nicacio. <a href="https://books.google.com.br/books?id=uxyluAEACAAJ">https://books.google.com.br/books?id=uxyluAEACAAJ</a>.
</div>
<div class="csl-entry">
RCoreTeam. 2020. <em>R Data Import/Export</em>. <em>Cran</em>. <a href="https://cran.r-project.org/doc/manuals/R-data.pdf">https://cran.r-project.org/doc/manuals/R-data.pdf</a>.
</div>
<div class="csl-entry">
Venables, W. N., and D. M. Smith. 2020. <em>An Introduction to r</em>. bookdown. <a href="https://colinfay.me/intro-to-r/">https://colinfay.me/intro-to-r/</a>.
</div>
<div class="csl-entry">
Wickham, Hadley, and Jennifer Bryan. 2019. <em>Readxl: Read Excel Files</em>. <a href="https://CRAN.R-project.org/package=readxl">https://CRAN.R-project.org/package=readxl</a>.
</div>
<div class="csl-entry">
Yamamoto, J. K. 2020. <em>Estatística, análise e Interpolação de Dados Geoespaciais</em>. 1st ed. São Paulo: Gráfica Paulos.
</div>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-DragulescuandArendt2007" class="csl-entry">
Dragulescu, Adrian, and Cole Arendt. 2020. <em>Xlsx: Read, Write, Format Excel 2007 and Excel 97/2000/XP/2003 Files</em>. <a href="https://CRAN.R-project.org/package=xlsx">https://CRAN.R-project.org/package=xlsx</a>.
</div>
<div id="ref-Kabacoff2015R" class="csl-entry">
Kabacoff, Robert I. 2015. <em><span class="nocase">R in Action</span></em>. Second. Manning. <a href="http://www.worldcat.org/isbn/9781617291388">http://www.worldcat.org/isbn/9781617291388</a>.
</div>
<div id="ref-MiraiSolutionsGmbH2020" class="csl-entry">
Mirai Solutions GmbH. 2020. <em>XLConnect: Excel Connector for r</em>. <a href="https://CRAN.R-project.org/package=XLConnect">https://CRAN.R-project.org/package=XLConnect</a>.
</div>
<div id="ref-perlin2018processamento" class="csl-entry">
Perlin, M. S. 2018. <em>Processamento e an<span>á</span>lise de Dados Financeiros e Econ<span>ô</span>micos Com o r</em>. Cl<span>ó</span>vis Nicacio. <a href="https://books.google.com.br/books?id=uxyluAEACAAJ">https://books.google.com.br/books?id=uxyluAEACAAJ</a>.
</div>
<div id="ref-RCoreTeam" class="csl-entry">
RCoreTeam. 2020. <em>R Data Import/Export</em>. <em>Cran</em>. <a href="https://cran.r-project.org/doc/manuals/R-data.pdf">https://cran.r-project.org/doc/manuals/R-data.pdf</a>.
</div>
<div id="ref-WickhamandBryan2019" class="csl-entry">
Wickham, Hadley, and Jennifer Bryan. 2019. <em>Readxl: Read Excel Files</em>. <a href="https://CRAN.R-project.org/package=readxl">https://CRAN.R-project.org/package=readxl</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="acessando-e-manipulação-de-dados.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Jacksonmrod/ENG.792-AVDR/edit/master/Cap_3.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/Cap_3.Rmd",
"text": null
},
"download": ["ENG_792-AVDR.pdf", "ENG_792-AVDR.epub"],
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
